"use  client";
import { AgGridReact } from "ag-grid-react"; // React Data Grid Component
import "ag-grid-community/styles/ag-grid.css"; // Mandatory CSS required by the grid
import "ag-grid-community/styles/ag-theme-quartz.css"; // Optional Theme applied to the grid
import { useState } from "react";

interface ITableProps {
  setOpenSideBar: (openSideBar: boolean) => void;
  openSideBar: boolean;
  setIsOtherSideBarContentVisible: (isVisible: boolean) => void;
}
const Table = ({ setOpenSideBar, openSideBar , setIsOtherSideBarContentVisible }: ITableProps) => {
  const [rowData, setRowData] = useState([
    {
      jcn: "23003058",
      jcn_status: "F",
      total_auth_amt: "",
      total_delphi_commit: "",
      total_delphi_obl: "",
      total_prism_commit: "",
      total_regis_commit: "",
      total_regis_oblig: "",
      cip: "AJI.00-00",
      cip_su: "",
      cip_title: "Technical Course Development Program Office",
      complexity: "",
      jcn_last_analyze_dt: "15-NOV-23",
      org_district_office: "",
      funded: "",
      in_baseline: "YES",
      project_code: "98000102",
      rtg_construction: "",
      rtg_construction_desc: "SKY, ROSEANNE",
      name_engr: "",
      rtg_engr: "DUNBAR, MICHAEL"
    },
    {
      "jcn": "1402941",
      "jcn_status": "F",
      "total_auth_amt": "",
      "total_delphi_commit": "",
      "total_delphi_obl": "",
      "total_prism_commit": "",
      "total_regis_commit": "",
      "total_regis_oblig": "",
      "cip": "F06.01-00",
      "cip_su": "",
      "cip_title": "ARTCC & CCF Sustainment",
      "complexity": "",
      "jcn_last_analyze_dt": "23-JUL-18",
      "org_district_office": "OAKLAND ARTCC GROUP",
      "funded": "",
      "in_baseline": "YES",
      "project_code": "20160519",
      "rtg_construction": "",
      "rtg_construction_desc": "DIAS, WOODY",
      "name_engr": "HOLGUIN, MONICA",
      "rtg_engr": "KITCHEN, DARYL",
    },
    {
      "jcn": "1200878",
      "jcn_status": "Z",
      "total_auth_amt": "",
      "total_delphi_commit": "",
      "total_delphi_obl": "",
      "total_prism_commit": "",
      "total_regis_commit": "",
      "total_regis_oblig": "",
      "cip": "M53.01-01",
      "cip_su": "",
      "cip_title": "AMEN - Technology Refresh Phase 1",
      "complexity": "",
      "jcn_last_analyze_dt": "08-JAN-18",
      "org_district_office": "",
      "funded": "",
      "in_baseline": "NO",
      "project_code": "",
      "rtg_construction": "",
      "rtg_construction_desc": "",
      "name_engr": "PLURA, ERIC",
      "rtg_engr": "",
    },
    {
      "jcn": "1002469",
      "jcn_status": "F",
      "total_auth_amt": "",
      "total_delphi_commit": "",
      "total_delphi_obl": "",
      "total_prism_commit": "",
      "total_regis_commit": "",
      "total_regis_oblig": "",
      "cip": "OPS.00-0W",
      "cip_su": "",
      "cip_title": "OPS Funding Technical Operations",
      "complexity": "",
      "jcn_last_analyze_dt": "11-NOV-19",
      "org_district_office": "MICHIGAN GROUP",
      "funded": "YES",
      "in_baseline": "NO",
      "project_code": "",
      "rtg_construction": "",
      "rtg_construction_desc": "",
      "name_engr": "",
      "rtg_engr": "BONTA, WAYNE; KEIL, CHRISTOPHER; WERNER, GREG",
    }, {
      "jcn": "23003106",
      "jcn_status": "N",
      "total_auth_amt": "",
      "total_delphi_commit": "",
      "total_delphi_obl": "",
      "total_prism_commit": "",
      "total_regis_commit": "",
      "total_regis_oblig": "",
      "cip": "",
      "cip_su": "",
      "cip_title": "",
      "complexity": "",
      "jcn_last_analyze_dt": "",
      "org_district_office": "PORTLAND GROUP",
      "funded": "",
      "in_baseline": "NO",
      "project_code": "",
      "rtg_construction": "",
      "rtg_construction_desc": "",
      "name_engr": "",
      "rtg_engr": "",
    },
    {
      "jcn": "1598198",
      "jcn_status": "F",
      "total_auth_amt": "",
      "total_delphi_commit": "",
      "total_delphi_obl": "",
      "total_prism_commit": "",
      "total_regis_commit": "",
      "total_regis_oblig": "",
      "cip": "R01.00-00",
      "cip_su": "",
      "cip_title": "F&E Funded Reimbursable Agreement Service Area Only",
      "complexity": "",
      "jcn_last_analyze_dt": "07-MAR-16",
      "org_district_office": "LOS ANGELES GROUP",
      "funded": "",
      "in_baseline": "NO",
      "project_code": "",
      "rtg_construction": "",
      "rtg_construction_desc": "",
      "name_engr": "",
      "rtg_engr": "",
    },

    {
      "jcn": "1602389",
      "jcn_status": "Z",
      "total_auth_amt": "",
      "total_delphi_commit": "",
      "total_delphi_obl": "",
      "total_prism_commit": "",
      "total_regis_commit": "",
      "total_regis_oblig": "",
      "cip": "F01.01-00",
      "cip_su": "",
      "cip_title": "ATCT/TRACON Sustainment",
      "complexity": "",
      "jcn_last_analyze_dt": "05-FEB-24",
      "org_district_office": "PACIFIC DESERT GROUP",
      "funded": "",
      "in_baseline": "NO",
      "project_code": "",
      "rtg_construction": "MILLER, CHUCK; DOBBINS, DESTAING",
      "rtg_construction_desc": "",
      "name_engr": "TORMANEN, MARK",
      "rtg_engr": "",
    },
    {
      "jcn": "23003173",
      "jcn_status": "Z",
      "total_auth_amt": "",
      "total_delphi_commit": "",
      "total_delphi_obl": "",
      "total_prism_commit": "",
      "total_regis_commit": "",
      "total_regis_oblig": "",
      "cip": "F12.00-00",
      "cip_su": "",
      "cip_title": "Unstaffed Infrastructure Sustainment (UIS)",
      "complexity": "",
      "jcn_last_analyze_dt": "",
      "org_district_office": "MICHIGAN GROUP",
      "funded": "",
      "in_baseline": "NO",
      "project_code": "98000502",
      "rtg_construction": "",
      "rtg_construction_desc": "",
      "name_engr": "",
      "rtg_engr": "",
    },
    {
      "jcn": "1701153",
      "jcn_status": "F",
      "total_auth_amt": "",
      "total_delphi_commit": "",
      "total_delphi_obl": "",
      "total_prism_commit": "",
      "total_regis_commit": "",
      "total_regis_oblig": "",
      "cip": "G06N.01-03",
      "cip_su": "",
      "cip_title": "NextGen Navigation Engineering",
      "complexity": "",
      "jcn_last_analyze_dt": "24-JUN-19",
      "org_district_office": "MISSOURI/KANSAS/OKLAHOMA GROUP",
      "funded": "",
      "in_baseline": "NO",
      "project_code": "",
      "rtg_construction": "",
      "rtg_construction_desc": "",
      "name_engr": "PLURA, ERIC",
      "rtg_engr": "",
    },
    {
      "jcn": "1501544",
      "jcn_status": "F",
      "total_auth_amt": "",
      "total_delphi_commit": "",
      "total_delphi_obl": "",
      "total_prism_commit": "",
      "total_regis_commit": "",
      "total_regis_oblig": "",
      "cip": "F13.01-00",
      "cip_su": "",
      "cip_title": "Fuel Storage Tank Sustainment",
      "complexity": "",
      "jcn_last_analyze_dt": "30-MAR-20",
      "org_district_office": "SOUTHERN ALASKA GROUP",
      "funded": "",
      "in_baseline": "YES",
      "project_code": "98220618",
      "rtg_construction": "",
      "rtg_construction_desc": "NEDOM, MATT",
      "name_engr": "",
      "rtg_engr": "CABODIE, FRANK",
    }


  ]);

  // Column Definitions: Defines the columns to be displayed.
  const [colDefs, setColDefs] = useState([
    {
      field: "jcn" as const,
      headerName: "JCN",
      cellRenderer: (params: any) => params.value.toString(),
      filter: 'agTextColumnFilter',
      floatingFilter: true,
    },
    { field: "jcn_status" as const, headerName: "JCN Status", filter: 'agTextColumnFilter', floatingFilter: true },
    { field: "total_auth_amt" as const, headerName: "Total Authorized Amount", filter: 'agNumberColumnFilter', floatingFilter: true },
    {
      field: "total_delphi_commit" as const,
      headerName: "Total Delphi Commitment",
      filter: 'agNumberColumnFilter',
      floatingFilter: true,
    },
    {
      field: "total_delphi_obl" as const,
      headerName: "Total Delphi Obligation",
      filter: 'agNumberColumnFilter',
      floatingFilter: true,
    },
    {
      field: "total_prism_commit" as const,
      headerName: "Total Prism Commitment",
      filter: 'agNumberColumnFilter',
      floatingFilter: true,
    },
    {
      field: "total_regis_commit" as const,
      headerName: "Total Regis Commitment",
      filter: 'agNumberColumnFilter',
      floatingFilter: true,
    },
    {
      field: "total_regis_oblig" as const,
      headerName: "Total Regis Obligation",
      filter: 'agNumberColumnFilter',
      floatingFilter: true,
    },
    { field: "cip" as const, headerName: "CIP", filter: 'agTextColumnFilter', floatingFilter: true },
    { field: "cip_su" as const, headerName: "CIP SU", filter: 'agTextColumnFilter', floatingFilter: true },
    { field: "cip_title" as const, headerName: "CIP Title", filter: 'agTextColumnFilter', floatingFilter: true },
    { field: "complexity" as const, headerName: "Complexity", filter: 'agTextColumnFilter', floatingFilter: true },
    { field: "jcn_last_analyze_dt" as const, headerName: "Last Analyze Date", filter: 'agDateColumnFilter', floatingFilter: true },
    {
      field: "org_district_office" as const,
      headerName: "Organization District Office",
      filter: 'agTextColumnFilter',
      floatingFilter: true,
    },
    { field: "funded" as const, headerName: "Funded", filter: 'agTextColumnFilter', floatingFilter: true },
    { field: "in_baseline" as const, headerName: "In Baseline", filter: 'agTextColumnFilter', floatingFilter: true },
    { field: "project_code" as const, headerName: "Project Code", filter: 'agTextColumnFilter', floatingFilter: true },
    { field: "rtg_construction" as const, headerName: "RTG Construction", filter: 'agTextColumnFilter', floatingFilter: true },
    {
      field: "rtg_construction_desc" as const,
      headerName: "RTG Construction Description",
      filter: 'agTextColumnFilter',
      floatingFilter: true,
    },
    { field: "name_engr" as const, headerName: "Name Engineer", filter: 'agTextColumnFilter', floatingFilter: true },
    { field: "rtg_engr" as const, headerName: "RTG Engineer", filter: 'agTextColumnFilter', floatingFilter: true },
    

  ]);
  return (
    <div className="ag-theme-quartz" style={{ height: 400, width: 1200 }}>
      <AgGridReact
        columnDefs={colDefs}
        rowData={rowData}
        onCellClicked={() => {setOpenSideBar(!openSideBar) 
          setIsOtherSideBarContentVisible(true)
        }}
      />
    </div>
  );
};

export default Table;
